alexandria-reader/backend

package-lock.json
package.json
src/routes/login.ts
src/routes/texts.ts
src/routes/users.ts
src/services/users.ts
src/utils/middleware.ts

I added in some boilerplate code for user creation, login, authentication, etc. It can't be used until the database is connected.

Added boilerplate for users, login routes

---

src/app.ts
src/model/db-query.ts
src/routes/texts.ts
src/routes/users.ts
src/services/users.ts
src/types.ts
tsconfig.json

I will introduce error checking in another branch later

Added basic user routes, post and get, and services to go along with it

---

src/model/db-query.ts
src/model/schema.sql
src/services/texts.ts
src/services/words.ts
src/types.ts

* Added function to find words by user and language.
* Added function to add texts.
* `services/texts.ts` and `services/words.ts` are now correctly typed.
* Added word and text types to `types.ts` and also conversion functions between `snake_case` DB results and `camelCase` types. 
* `db-query.ts` is now correctly typed.
* Tiny modification to the DB schema.
* Used backticks for the SQL queries for more readable formatting (eg. multiline).

more text and word services, correctly typed

---

src/app.ts
src/routes/texts.ts
src/routes/words.ts
src/services/words.ts

- `routes/words.ts` added
- small fix on `services/words.ts` to return words list instead of single word
- small fix on `routes/texts.ts`, on variable naming of `text` instead of `texts`

Add words route

---

src/routes/users.ts
src/services/users.ts

Added user update password route, put a schema in for 2 more routes, and some comments on what to do next.

Ea user routes services

---

.gitignore
src/app.ts
src/model/env
src/model/schema.sql
src/model/seed.sql
src/routes/texts.ts
src/routes/words.ts
src/services/languages.ts
src/services/texts.ts
src/services/webdictionaries.ts
src/services/words.ts
src/types.ts

Added language, texts and words services and appropriate types and conversion functions. 
There is also an updated schema in there that takes text titles into account when looking for known userwords. Is not easy to implement without all tables relating to texts. But it is also not urgent to do it on the staging DB.

mh services - fairly large update to language, word, and text services

---

package.json
src/routes/translations.ts
src/routes/words.ts
src/services/translations.ts
src/services/words.ts
src/types.ts

- Added routes for translations
- Added services for translations
- Edited words routes
Comments: 
- Might need to move around things based on some of the other services and routes. There's still at least a couple more routes I want to implement, but would prefer to spot any issues at the moment.
- Naming is not consistent with the latest changes, can be changed when merging or in next commit.

Dc translations services

---

src/routes/words.ts
src/services/words.ts

Resolved naming conflicts between services and routes. 
Important: `db-query` of updating a table doesn't return rows. If you want to return an updated item, you have to query for it in the service and return it at the end of the update service function.

func names in words routes/services, and cleanup

---

.eslintrc
jest.config.js
package.json
src/app.ts
src/model/db-query.ts
src/model/env
src/routes/users.ts
src/tests/userTests.test.ts

I've added a separate db for testing, runs on test env. You need to add the URI from heroku.

Added some basic testing functionality and dependencies

---

package.json
src/model/test-db-reset.ts
src/tests/userTests.test.ts

I export an array of DELETE FROM commands, run through them before the tests. Only works when using Jest.

I set up the tests so that the test db is reset when the tests start running

---

src/routes/users.ts
src/services/users.ts
src/tests/userTests.test.ts

The 3rd test (adding a duplicate user) makes jest not exit cleanly although the tests still work, I will fix it in a future update.

Added more robust error handling for duplicate users, changed default export of users to userServices Object

---

.github/workflows/postgres.yaml
.gitignore
client.js
package-lock.json
package.json
src/model/db-query.ts
src/types.ts

To do this I needed to make a slight change to `db-query.ts` as the current format is incompatible with the container version.

Added github action that creates a docker container psql db and auto runs tests

---

.gitignore
src/services/texts.ts
src/services/words.ts

A ton of changes and additions throught the text and word services. Now includes the search for known userwords in a given text.

mh word text services 

---

src/routes/translations.ts
src/routes/words.ts
src/services/translations.ts
src/services/words.ts

- Naming of service functions updated
- Route and services updated
- words post route '/' pending discussion around what the service function `addNew` should return

Updated translations routes and services, words route

---

src/services/texts.ts
src/services/words.ts

I had forgotten to fill that column in the `INSERT` query. Also spotted and fixed a syntax error in `services/texts.ts`. 
Hope it works now.

(hopefully) fixed ts_config bug in services

---

src/routes/translations.ts
src/routes/words.ts
src/services/translations.ts
src/services/words.ts

- Updated words route and translation services, merge before more conflicts arise out of Marc working on same file for words route

Update words route based on service, translation remove service

---

src/model/test-db-before.ts
src/routes/translations.ts
src/services/translations.ts
src/tests/translations.test.ts
src/tests/userTests.test.ts

- tests added for translations routes
- database reset using `test-db-reset.ts`

Testing for translations routes

---

src/app.ts
src/model/db-query.ts
src/model/seed.sql
src/model/test-db-reset.ts
src/routes/users.ts
src/routes/words.ts
src/services/languages.ts
src/services/texts.ts
src/services/users.ts
src/services/webdictionaries.ts
src/services/words.ts
src/tests/userTests.test.ts
src/types.ts
src/utils/errorHandlers.ts

* Implemented handling of existing username/email in `services/users.ts`.
* Changed `routes/texts.ts` and `tests/userTests.test.ts` accordingly. 
* Minor refactors to other routes and services. 
What I like about the approach using `boom` for error handling is that the middleware is generic (no filtering for types) and we can use `throw boom.httpErrorName('message')` anywhere to send back a formatted, status-coded error message to the front end. Check it out in `services/users.ts` or open [text 666](http://localhost:3000/api/texts/666) and see how easy it is.

mh more errorhandling

---

READ.md
package.json
postgres.yaml
src/model/env
src/routes/users.ts
src/services/users.ts

To test this out, set TEST_DATABASE_URL="postgres://user:password@0.0.0.0:8080/test" in your .env file.
Instructions for Docker container are in the READ.md file

Added postgres docker test db, added user delete route and service

---

package.json
src/model/wordServices.test.init.sql
src/model/wordServices.test.reset.sql
src/routes/words.ts
src/services/words.ts
src/tests/translations.test.ts
src/tests/wordSevices.test.ts

Finally! Tests! For word services! Had to update the routes a bit for slightly changed typing. Services return `null` now, when nothing is found.

mh word service tests

---

src/model/schema.sql
src/model/seed.sql
src/model/test-db-before.ts
src/model/test-db-reset.ts
src/model/wordServices.test.init.sql
src/model/wordServices.test.reset.sql

New schema passes check on GitHub now, and - with a little workaround - on Docker PG (see my long explanation in Slack).

mh schema update

---

src/routes/translations.ts
src/routes/words.ts
src/services/translations.ts
src/tests/transServices.test.ts
src/tests/translations.test.ts
src/tests/wordsRoutes.test.ts

Includes:
[x] add translations services tests
[x] broke up a couple of services into smaller units
[x] re-wrote tests for broken services
[x] typing translations services
[x] add delete route for words
[x] add delete test for words route

Translations services testing

---

src/model/test-db-before.ts
src/routes/words.ts
src/services/contexts.ts
src/services/translations.ts
src/tests/transServices.test.ts
src/tests/wordsRoutes.test.ts
src/types.ts

- add `contexts` types
- add `contexts` services
- add `contexts` tests
- fix return code for `words` delete route and `words` delete route test

Add contexts related files

---

.github/workflows/postgres.yaml
src/data-access/languages.ts
src/data-access/texts.ts
src/data-access/webdictionaries.ts
src/data-access/words.ts
src/routes/texts.ts
src/routes/words.ts
src/services/languages.ts
src/services/texts.ts
src/services/webdictionaries.ts
src/services/words.ts
src/tests/languageServices.test.ts
src/tests/textServices.test.ts
src/tests/wordServices.test.ts

Oh, and I renamed the "container-job" to "pg-test-job".

layers refactor texts, words, languages, webdicts

---

package-lock.json
package.json
src/data-access/contexts.ts
src/data-access/languages.ts
src/data-access/texts.ts
src/data-access/translations.ts
src/data-access/users.ts
src/data-access/webdictionaries.ts
src/data-access/words.ts
src/routes/translations.ts
src/services/contexts.ts
src/services/translations.ts
src/tests/transServices.test.ts
src/tests/translations.test.ts

[x] Break up data and service layers for translations and contexts
[x] Eliminate retrieving translations by word id, update routes previously requiring word id
[x] Update translations services with boom
[x] Update context services/data-access

Refactoring translations/contexts to reflect 3-layer model

---

src/data-access/texts.ts
src/model/schema.sql
src/model/test-db-before.ts
src/model/test-db-reset.ts

* Added `last_opened` timestamp column to `texts`table.
* Returning list of user texts ordered by `last_opened`.

mh texts schema

---

src/routes/texts.ts
src/routes/words.ts

- Route to retrieved matched words (api/words/text/:id/user/:id)
- Should be moved to `texts` later when typed properly

Add test route to words

---

package.json
src/model/reset.sql
src/model/schema.sql
src/model/seed.sql

`username` no longer `UNIQUE` but still called `username` so I wouldn't have to update 15 other files.
Also tiny addition of `cross-env` to the `test` script to make it run on Windows.

schema update for username

---

src/data-access/users.ts
src/routes/users.ts
src/services/users.ts
src/types.ts

Tested with Postman and current front end form to make sure backend isn't broken. Can add user and log back in with password.

Update users routes/services/data access for frontend user creation

---

src/data-access/texts.ts
src/routes/texts.ts
src/services/texts.ts

I added a new route to get texts filtered by user and language

Ea texts by language

---

src/app.ts
src/routes/languages.ts
src/routes/texts.ts
src/routes/translations.ts
src/routes/users.ts
src/routes/words.ts
src/services/users.ts
src/tests/textRoutes.test.ts
src/tests/translations.test.ts
src/tests/users.test.ts
src/tests/wordsRoutes.test.ts
src/types.ts

* Added new type `UserTranslation` that extends `Translation` with the user specific context.
* Changed type `UserWord`: removed `contexts` property, and `translations` property now holds an array of `UserTranslation`
* Commented the `Context`related types out.
closes #80 
|     | :bug: Bug fix              |
|     | :sparkles: New feature     |
| ✓   | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |
Content services might throw type errors now, but I think they are obsolete anyway.

mh type changes

---

src/routes/translations.ts

Fixed a bug where translations were not being added. Changed translation to translations. Added an id check to allow addToUsersTranslations to call successfully.
|  X | :bug: Bug fix              |
|     | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

Bug fix in `POST /translations` route

---

.eslintrc
Procfile
package.json
src/app.ts
src/data-access/contexts.ts
src/model/db-query.ts
src/services/contexts.ts
src/tests/transServices.test.ts
src/types.ts
tsconfig.json

Reverts alexandria-reader/backend#97

Revert "Mh build script"

---

src/data-access/words.ts

Fixed property names returned by a data-access function that is required by words page on front end. 
| :heavy_check_mark:     | :bug: Bug fix              |

fixed data-access for userwords in language

---

src/model/seed.sql

Tiny update to `seed.sql` to properly set user languages. 
| :heavy_check_mark:     | :bug: Bug fix              |

updated seed with user languages

---

src/data-access/languages.ts
src/model/reset.sql
src/model/schema.sql
src/model/seed.sql
src/tests/languageServices.test.ts
src/types.ts

* added `flag` property to language related types
* updated `addNew` function in `data-access` to include flag
* updated `schema.sql`, `seed.sql`, and `reset.sql`
**Databases need to be updated for this to work**
**Merge this PR _before_ the corresponding front end PR**
Closes #109 
| :heavy_check_mark:      | :sparkles: New feature     |

added language flag support

---

src/routes/users.ts
src/services/login.ts
src/services/users.ts
src/services/words.ts
src/types.ts

Lots of changes in preparation for the great front end state refactor. 
* `User` type know holds either language IDs or language objects. 
*  Services and routes adjusted to return users of new type.
*  Added `GET /api/users/from-token` route to, well, get a user based on the token found in local storage. 
This PR needs to get merged before the corresponding front end PR.
| :heavy_check_mark:     | :sparkles: New feature     |
|  :heavy_check_mark:    | :hammer: Refactoring       |
Test thoroughly, please, as there are many crucial changes.

Mh user languages (back end)

---

src/routes/users.ts
src/services/login.ts
src/tests/languageServices.test.ts
src/tests/login.test.ts

Spent almost an hour trying to fix the login test. Turned out, the test did not run `seed.sql`, so the database had no languages set.

fixed tests after refactor

---

src/routes/users.ts
src/services/login.ts
src/tests/languageServices.test.ts
src/tests/login.test.ts

Reverts alexandria-reader/backend#114

Revert "fixed tests after refactor"

---

src/routes/users.ts
src/services/login.ts
src/services/users.ts
src/services/words.ts
src/types.ts

Reverts alexandria-reader/backend#113

Revert "Mh user languages (back end)"

---

src/data-access/users.ts
src/model/reset.sql
src/model/schema.sql
src/model/seed.sql
src/routes/users.ts
src/services/login.ts
src/services/users.ts
src/services/words.ts
src/tests/languageServices.test.ts
src/tests/login.test.ts
src/tests/textRoutes.test.ts
src/tests/textServices.test.ts
src/tests/transServices.test.ts
src/tests/translations.test.ts
src/tests/users.test.ts
src/tests/wordServices.test.ts
src/tests/wordsRoutes.test.ts
src/types.ts

Here we go again! 
* I have taken a step back from the idea of optionally nesting Language objects in the User type. Too many conditionals involved. We're back to just language id, the front end handles the rest.
* I have stripped the prefix "current" from the user languages everywhere
* The two language properties are now mandatory properties
* I have updated the `schema.sql` etc. accordingly.
| :heavy_check_mark:     | :bug: Bug fix              |
| :heavy_check_mark:     | :hammer: Refactoring       |
**TEST THOROUGHLY, MERGE RESPONSIBLY**

Mh user languages 2 (back end)

---

src/data-access/users.ts
src/routes/users.ts
src/services/users.ts

|     | :bug: Bug fix              |
|     | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

Add new data, service and route for updating user info on front end

---

src/data-access/texts.ts

order texts by upload time, newest first

---

src/data-access/words.ts
src/services/words.ts

A small change to the highlighting (ie. bold) of the words in the context in the words table. It is now language specific and omits small common words.

language specific context highlighting

---

src/data-access/translations.ts
src/routes/translations.ts
src/services/translations.ts
src/tests/transServices.test.ts

Translation routes return 204 after deletion or an updated UserTranslation object after update. 
Closes #130 
Closes #131 
| :heavy_check_mark:     | :bug: Bug fix              |

mh fixes 130 131

---

package-lock.json
src/data-access/texts.ts
src/model/reset.sql
src/model/schema.sql
src/model/seed-production.sql
src/model/seed.sql
src/services/users.ts
src/tests/textServices.test.ts
src/tests/wordServices.test.ts

This update adds a demo text - the beginning of The Little Match Girl - to each new user in the language they intended to learn at signup.
Schema & seed updated. Database reset necessary for testing and eventual merge.
Should work with any front end. 
| :heavy_check_mark:     | :sparkles: New feature     |

Mh match girl

---

src/services/users.ts

Fixed link URL in verification email.

fixed  URL

---

src/services/users.ts

Verification emails are now sent via noreply@tryalexandria.com

changed email address

---

src/routes/users.ts
src/services/users.ts

…letion route
Added user password verification route, removed password from user deletion route (as password can't be sent with delete requests, the verification is done first).
|     | :bug: Bug fix              |
|     | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

Updated routes to deal with user deletion.

---

src/routes/users.ts

Minor change in route names to avoid confusion with email verification route.

renamed deletion verification to "confirm"

---

package-lock.json
src/data-access/languages.ts
src/data-access/texts.ts
src/data-access/translations.ts
src/data-access/users.ts
src/data-access/webdictionaries.ts
src/data-access/words.ts
src/routes/languages.ts
src/routes/login.ts
src/routes/texts.ts
src/routes/translations.ts
src/routes/url.ts
src/routes/users.ts
src/routes/verify.ts
src/routes/webdictionaries.ts
src/routes/words.ts
src/services/languages.ts
src/services/texts.ts
src/services/translations.ts
src/services/users.ts
src/services/webdictionaries.ts
src/services/words.ts
src/tests/languageServices.test.ts
src/tests/textServices.test.ts
src/tests/transServices.test.ts
src/tests/wordServices.test.ts
src/utils/sendmail.ts

Removed unused routes, services and data access functions from the code. Updated tests accordingly. 
This needs the corresponding front end update to work. 
|  :heavy_check_mark:    | :hammer: Refactoring       |

Mh cleanup
